import type { Metadata } from "next";
import { Geist, Geist_Mono, Old_Standard_TT, Roboto } from "next/font/google";
import "./globals.css";

const oldStandardTT = Old_Standard_TT({
  weight: ["400", "700"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${oldStandardTT.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
